services:
  - type: web
    name: yantra-daan-frontend
    env: static
    plan: free
    region: oregon
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NPM_VERSION
        value: 9.0.0
      - key: RENDER_BUILD_COMMAND
        value: npm ci && npm run build
      - key: RENDER_PUBLISH_DIRECTORY
        value: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
